import jsPDF from "jspdf";
import { Document, Packer, Paragraph, TextRun, HeadingLevel } from "docx";

export async function generatePDF(
  content: string,
  date: string,
  companyName?: string
): Promise<Uint8Array> {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  // Dark background
  doc.setFillColor(9, 9, 11);
  doc.rect(0, 0, 210, 297, "F");

  // Header bar
  doc.setFillColor(124, 58, 237);
  doc.rect(0, 0, 210, 8, "F");

  // Header text
  doc.setFont("Courier", "bold");
  doc.setFontSize(7);
  doc.setTextColor(255, 255, 255);
  doc.text(
    `ASHXCRIBE  //  SCRUM DOCUMENT  //  ${date}${companyName ? `  //  ${companyName.toUpperCase()}` : ""}`,
    10,
    5.5
  );

  // Divider
  doc.setDrawColor(63, 63, 70);
  doc.line(10, 14, 200, 14);

  // Body content
  doc.setFont("Courier", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(228, 228, 231);

  const lines = doc.splitTextToSize(content, 188);
  let y = 20;
  const pageHeight = 285;
  const lineHeight = 4.5;

  for (const line of lines) {
    if (y + lineHeight > pageHeight) {
      doc.addPage();
      doc.setFillColor(9, 9, 11);
      doc.rect(0, 0, 210, 297, "F");
      y = 15;
    }
    // Color section headers (lines starting with a digit or emoji)
    if (/^[1-5]\./.test(line) || /^[🛠>]/.test(line)) {
      doc.setTextColor(167, 139, 250);
    } else if (/^Date:|^Project\/Company:|^Sprint/.test(line)) {
      doc.setTextColor(129, 140, 248);
    } else {
      doc.setTextColor(228, 228, 231);
    }
    doc.text(line, 10, y);
    y += lineHeight;
  }

  // Footer
  doc.setFont("Courier", "normal");
  doc.setFontSize(7);
  doc.setTextColor(63, 63, 70);
  doc.text("Generated by Ashxcribe", 10, 292);

  return new Uint8Array(doc.output("arraybuffer"));
}

export async function generateDOCX(
  content: string,
  date: string,
  companyName?: string
): Promise<Uint8Array> {
  const headerText = `ASHXCRIBE // SCRUM DOCUMENT // ${date}${companyName ? ` // ${companyName.toUpperCase()}` : ""}`;

  const paragraphs: Paragraph[] = [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [
        new TextRun({
          text: headerText,
          bold: true,
          font: "Courier New",
          size: 20,
          color: "7C3AED",
        }),
      ],
      spacing: { after: 200 },
    }),
    ...content.split("\n").map(
      (line) =>
        new Paragraph({
          children: [
            new TextRun({
              text: line || " ",
              font: "Courier New",
              size: 18,
              color: line.match(/^[1-5]\./) ? "A78BFA" : "374151",
            }),
          ],
          spacing: { after: 60 },
        })
    ),
    new Paragraph({
      children: [
        new TextRun({
          text: "Generated by Ashxcribe",
          font: "Courier New",
          size: 14,
          color: "9CA3AF",
          italics: true,
        }),
      ],
      spacing: { before: 400 },
    }),
  ];

  const docxDoc = new Document({ sections: [{ children: paragraphs }] });
  const buf = await Packer.toBuffer(docxDoc);
  return new Uint8Array(buf);
}
